service: my-fastapi-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-1  # Change this to your desired AWS region

functions:
  app:
    handler: main.handler
    environment:
      ENV_VAR_1: value1
      ENV_VAR_2: value2

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    strip: false
    noDeploy: []

